module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    testMatch: ['**/*.steps.ts', '**/*.test.ts'],
    collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*/index.ts',
        '!src/**/*/Server.ts',
        '!src/index.ts',
        '!src/common/modules/ModulesFactory.ts',
        '!src/common/decorators/**',
        '!src/common/dependencies/Types.ts',
        '!src/common/http/**',
        '!src/common/modules/**',
        '!src/common/utils/**',
        '!src/infrastructure/app/**',
        '!src/infrastructure/bd/postgresql/adapter/**',
        '!src/infrastructure/pubsub/**',
        '!src/infrastructure/client/**',
        '!src/infrastructure/redis/adapter/**',
        '!src/modules/shared/**',
        '!src/modules/HealthCheck/**',
        '!src/modules/**/schemas/**',
        '!src/modules/**/constants/**',
        '!src/modules/**/dependencies/**',
        '!src/modules/**/test/**',
        '!**/__mocks__/**',
    ],
    coverageDirectory: './coverage/',
    collectCoverage: true,
    moduleNameMapper: {
        '^@application/(.*)$': '<rootDir>/src/application/$1',
        '^@domain/(.*)$': '<rootDir>/src/domain/$1',
        '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
        '^@configuration/(.*)$': '<rootDir>/src/configuration/$1',
        '^@common/(.*)$': '<rootDir>/src/common/$1',
        '^@modules/(.*)$': '<rootDir>/src/modules/$1',
        '^@configuration$': '<rootDir>/src/configuration/index',
        '^@util$': '<rootDir>/src/util/index',
        '^@modules$': '<rootDir>/src/modules/index',
        '^@common$': '<rootDir>/src/common/index',

    },
    setupFiles: ['<rootDir>/jest.setup.ts'],
};
